
defaults:
  - scope:
      path: ""
    values:
      # This description will be used for any page/post that does not defined its own.
      description: A 3D design created in vZome.  Use your mouse or touch to interact.

theme: jekyll-theme-cayman

exclude:
  # This is necessary to support older versions of vZome,
  #  to avoid generating extra pages in Jekyll, which clutter up the
  #  header for the minima theme, and probably others.
  - 2021/*/*/*/README.md
