
url: https://vorth.github.io

defaults:
  - scope:
      path: ""
    values:
      description: A 3D design created in vZome.  Use mouse or touch to interact.

theme: minima

exclude:
  - 2021/*/*/*/README.md
