title: Geometry With vZome
author: Scott Vorthmann
description: > # this means to ignore newlines until "defaults:"
  Geometric designs and stories,
  all created with vZome (https://vzome.com).

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "vzome"
      author: "Scott Vorthmann"
      # This description will be used for any page/post that does not define its own.
      description: A 3D design created in vZome.  Use your mouse or touch to interact.

exclude:
  # Don't generate pages from vZome-created README files,
  #  to avoid generating extra pages in Jekyll, which clutter up the
  #  header for the minima theme, and probably others.
  - 20*/*/*/*/README.md

show_excerpts: false # set to true to show excerpts on the homepage

paginate: 6  # requires jekyll-paginate gem

minima:
  date_format: "%b %-d, %Y"

# social links
twitter_username: vZome
facebook_username: vZome
youtube_username: vZome
github_username:  vZome
# instagram_username: vzome_geometry
# rss: rss
# dribbble_username: vZome
# flickr_username: vZome
# linkedin_username: NONE
# pinterest_username: NONE

header_pages:
- about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate

