
name: Build Jekyll Manually

on:
  workflow_dispatch:

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true
      - name: Archive the site
        uses: actions/upload-artifact@v2
        with:
          name: site-build
          path: build
