
name: vZome Twitter bot

on:
  workflow_dispatch:
  schedule:
    # 1PM UTC = 8AM EST
    - cron:  '0 13 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: step1
        name: Select a URL to tweet
        run: |
          URL=$( node scripts/chooseDesignUrl.js )
          echo "::set-output name=tweeturl::$URL"
      - id: step2
        uses: ethomson/send-tweet-action@v1
        with:
          status: "${{ steps.step1.outputs.tweeturl }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
